plugins:
  swagger: ../swagger-routing-controllers

annotations:
  text:
  - title
  - description
  - format
  - pattern
  json: []
decorators:
  controller:
    - name: Controller
      type:
        - class
      resolver: ./dist/lib/decorator-resolver/ControllerDecoratorResolver.js

    - name: JsonController
      type:
        - class
      resolver: ./dist/lib/decorator-resolver/ControllerDecoratorResolver.js

  method:
    - name: Get
      type:
        - endpoin
        - method

    - name: Post
      type:
        - endpoin
        - method

    - name: Put
      type:
        - endpoin
        - method

    - name: Patch
      type:
        - endpoin
        - method

    - name: Delete
      type:
        - endpoin
        - method

    - name: Head
      type:
        - endpoin
        - method

    - name: HttpCode
      type:
        - method
        - response

    - name: OnUndefined
      type:
        - method
        - response

    - name: OnNull
      type:
        - method
        - response

    - name: Header
      type:
        - method
        - response

    - name: ContentType
      type:
        - method
        - response

    - name: Redirect
      type:
        - method
        - response

  parameter:
    - name: Param
      type:
        - parameter

    - name: Params
      type:
        - parameter

    - name: QueryParam
      type:
        - parameter

    - name: QueryParams
      type:
        - parameter

    - name: HeaderParam
      type:
        - parameter

    - name: HeaderParams
      type:
        - parameter

    - name: CookieParam
      type:
        - parameter

    - name: Body
      type:
        - parameter

    - name: BodyParam
      type:
        - parameter

    - name: UploadedFiles
      type:
        - parameter

    - name: UploadedFile
      type:
        - parameter
